/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import florist.florist;
import javax.swing.JOptionPane;

public class create extends javax.swing.JFrame {

    /**
     * Creates new form create
     */
    public create() {
        initComponents();
        setLocationRelativeTo(null);  
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtpricestalk = new javax.swing.JTextField();
        txtpricedozen = new javax.swing.JTextField();
        txtColor = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 413, 110, 40));

        txtID.setBackground(new java.awt.Color(222, 201, 182));
        txtID.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setBorder(null);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 210, 30));

        txtName.setBackground(new java.awt.Color(222, 201, 182));
        txtName.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setBorder(null);
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 210, 30));

        txtStock.setBackground(new java.awt.Color(222, 201, 182));
        txtStock.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        txtStock.setForeground(new java.awt.Color(255, 255, 255));
        txtStock.setBorder(null);
        getContentPane().add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 210, 30));

        txtpricestalk.setBackground(new java.awt.Color(222, 201, 182));
        txtpricestalk.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        txtpricestalk.setForeground(new java.awt.Color(255, 255, 255));
        txtpricestalk.setBorder(null);
        getContentPane().add(txtpricestalk, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 210, 30));

        txtpricedozen.setBackground(new java.awt.Color(222, 201, 182));
        txtpricedozen.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        txtpricedozen.setForeground(new java.awt.Color(255, 255, 255));
        txtpricedozen.setBorder(null);
        getContentPane().add(txtpricedozen, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 210, 30));

        txtColor.setBackground(new java.awt.Color(222, 201, 182));
        txtColor.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        txtColor.setForeground(new java.awt.Color(255, 255, 255));
        txtColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Yellow", "Orange", "Pink", "Purple", "White", "Green" }));
        getContentPane().add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 220, 30));

        save.setContentAreaFilled(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 120, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LOGIN (13).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new mainmenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        //java.sql.Date df = new java.sql.Date(tanggal.getDate(). getTime());
        String ID = txtID.getText().trim();
        String Name = txtName.getText().trim();
        int Stock = Integer.parseInt(txtStock.getText().trim());
        String Color = (String) txtColor.getSelectedItem();

        // Validate and parse PriceStalk
        int PriceStalk;
        try {
            PriceStalk = Integer.parseInt(txtpricestalk.getText().trim());
            if (PriceStalk <= 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "PriceStalk must be a positive integer");
            return; // Stop execution if validation fails
        }

        // Validate and parse PriceDozen
        int PriceDozen;
        try {
            PriceDozen = Integer.parseInt(txtpricedozen.getText().trim());
            if (PriceDozen <= 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "PriceDozen must be a positive integer");
            return; // Stop execution if validation fails
        }

        if (ID.isEmpty() || Name.isEmpty() || Color.isEmpty()) { 
            JOptionPane.showMessageDialog(this, "Empty data is not allowed!");
        } else { 
            florist Florist = new florist();
            Florist.ID = ID;
            Florist.name = Name;
            Florist.stock = Stock;
            Florist.color = Color;
            Florist.priceStalk = PriceStalk;
            Florist.priceDozen = PriceDozen;

            if (Florist.create()) {
                JOptionPane.showMessageDialog(this, "Data has been successfully saved!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to save data!");
            }
        }

         
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new create().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> txtColor;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtpricedozen;
    private javax.swing.JTextField txtpricestalk;
    // End of variables declaration//GEN-END:variables
}
